### ISSUE TITLE
Wrong urls

### ISSUE THREAD

**Issue by acrive82** [thewhitetulip/awk-anti-textbook#1]
All URL point to wrong content (Gitbooks, leanpub, youtube, etc).

**Comment by duraki** [comment]
When you push copied StackOverflow code to production

**Comment by benkoshy** [comment]
I couldn't find the correct links so I took them down for the moment with this PR:  #4 - they can be added later on when the gitbooks / leanpub books have been created

i hope this helps.

**Comment by thewhitetulip** [comment]
@duraki this is what happens when you develop open source code in the open, as opposed to create everything at home and then upload the entire project 😄 

issue is closed #4 Thank you @BKSpurgeon
