### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by xyjprc** [thewhitetulip/awk-anti-textbook#9]
In manuscript/1.0file.md

Typo: **FOr** that matter...

Incorrect result: printing odd lines:

         code ⏰  awk 'NR % 2 == 0 {print}' sales.csv
         Jan,100
        **Feb,200**
         March,100
         May,900
         July,10

**Comment by xyjprc** [comment]
3.0advanced.md
Example 1 should remove -OFS=","

**Comment by thewhitetulip** [comment]
1. Typo fixed
2. NR%2==0 : updated the output by running the query again on the same file. I think I messed up the file update. That's why the output isn't matching with what you're expecting
3. Fixed.

Thank you for creating this issue!
